export const CoreComponents = {
    // ChildMap                     : "ChildMap",
    CoreAccordion                : "CoreAccordion",
    CoreAccordionDetail          : "CoreAccordionDetail",
    CoreAccordionSummary         : "CoreAccordionSummary",
    CoreAlert                    : "CoreAlert",
    CoreApiVersion               : "CoreApiVersion",
    CoreAppBar                   : "CoreAppBar",
    CoreAppDiv                   : "CoreAppDiv",
    CoreAppVersion               : "CoreAppVersion",
    CoreAsyncSelect              : "CoreAsyncSelect",
    CoreAutocomplete             : "CoreAutocomplete",
    CoreAvatar                   : "CoreAvatar",
    CoreBackdrop                 : "CoreBackdrop",
    CoreBadge                    : "CoreBadge",
    CoreBox                      : "CoreBox",
    CoreButton                   : "CoreButton",
    CoreCard                     : "CoreCard",
    CoreCardActionArea           : "CoreCardActionArea",
    CoreCardActions              : "CoreCardActions",
    CoreCardContent              : "CoreCardContent",
    CoreCardHeader               : "CoreCardHeader",
    CoreCardMedia                : "CoreCardMedia",
    CoreCheckbox                 : "CoreCheckbox",
    CoreChip                     : "CoreChip",
    CoreCircularProgress         : "CoreCircularProgress",
    CoreCollapse                 : "CoreCollapse",
    CoreConfirmPassword          : "CoreConfirmPassword",
    CoreConfirmPasswordField     : "CoreConfirmPasswordField",
    CoreContainedButton          : "CoreContainedButton",
    CoreContainer                : "CoreContainer",
    CoreCustomTabs               : "CoreCustomTabs",
    CoreDataTable                : "CoreDataTable",
    CoreDataTableBody            : "CoreDataTableBody",
    CoreDataTableDetailsPane     : "CoreDataTableDetailsPane",
    CoreDataTableFooter          : "CoreDataTableFooter",
    CoreDataTableHead            : "CoreDataTableHead",
    CoreDataTableRow             : "CoreDataTableRow",
    CoreDataTableRowActionPopover: "CoreDataTableRowActionPopover",
    CoreDataTableRowContent      : "CoreDataTableRowContent",
    CoreDataTableRowSummary      : "CoreDataTableRowSummary",
    CoreDataTableToolbar         : "CoreDataTableToolbar",
    CoreDateRangepicker          : "CoreDateRangepicker",
    CoreDateTimePicker           : "CoreDateTimePicker",
    CoreDateTimeRangePicker      : "CoreDateTimeRangePicker",
    CoreDatepicker               : "CoreDatepicker",
    CoreDialog                   : "CoreDialog",
    CoreDivider                  : "CoreDivider",
    CoreDrawer                   : "CoreDrawer",
    CoreEditForm                 : "CoreEditForm",
    CoreEmailLink                : "CoreEmailLink",
    CoreEmailOrPhoneLink         : "CoreEmailOrPhoneLink",
    CoreFab                      : "CoreFab",
    CoreFade                     : "CoreFade",
    CoreFieldButton              : "CoreFieldButton",
    CoreFilePicker               : "CoreFilePicker",
    CoreFlatList                 : "CoreFlatList",
    CoreFooter                   : "CoreFooter",
    CoreForm                     : "CoreForm",
    CoreFormButton               : "CoreFormButton",
    CoreFormContainer            : "CoreFormContainer",
    CoreFormControl              : "CoreFormControl",
    CoreFormDialogs              : "CoreFormDialogs",
    CoreFormErrorText            : "CoreFormErrorText",
    CoreFormField                : "CoreFormField",
    CoreFormGroup                : "CoreFormGroup",
    CoreFormGroupLabel           : "CoreFormGroupLabel",
    CoreFormHeader               : "CoreFormHeader",
    CoreFormHeaderActions        : "CoreFormHeaderActions",
    CoreFormHelperText           : "CoreFormHelperText",
    CoreFormLabelCheckbox        : "CoreFormLabelCheckbox",
    CoreGoogleButton             : "CoreGoogleButton",
    CoreGrid                     : "CoreGrid",
    CoreGridItem                 : "CoreGridItem",
    CoreH                        : "CoreH",
    CoreH1                       : "CoreH1",
    CoreH2                       : "CoreH2",
    CoreH3                       : "CoreH3",
    CoreH4                       : "CoreH4",
    CoreH5                       : "CoreH5",
    CoreH6                       : "CoreH6",
    CoreIcon                     : "CoreIcon",
    CoreIconButton               : "CoreIconButton",
    CoreIconText                 : "CoreIconText",
    CoreImage                    : "CoreImage",
    CoreImageBackground          : "CoreImageBackground",
    CoreImagePicker              : "CoreImagePicker",
    CoreInput                    : "CoreInput",
    CoreInputAdornment           : "CoreInputAdornment",
    CoreInputLabel               : "CoreInputLabel",
    CoreInputPassword            : "CoreInputPassword",
    CoreJSONEditor               : "CoreJSONEditor",
    CoreJSONInput                : "CoreJSONInput",
    CoreLabel                    : "CoreLabel",
    CoreLinearProgress           : "CoreLinearProgress",
    CoreLink                     : "CoreLink",
    CoreList                     : "CoreList",
    CoreListItem                 : "CoreListItem",
    CoreListItemButton           : "CoreListItemButton",
    CoreListItemIcon             : "CoreListItemIcon",
    CoreListItemText             : "CoreListItemText",
    CoreLoginDetails             : "CoreLoginDetails",
    CoreMarkdownViewer           : "CoreMarkdownViewer",
    CoreMedicineSelector         : "CoreMedicineSelector",
    CoreMenu                     : "CoreMenu",
    CoreMenuItem                 : "CoreMenuItem",
    CoreMenuList                 : "CoreMenuList",
    CoreModal                    : "CoreModal",
    CoreMultiTimeRangePicker     : "CoreMultiTimeRangePicker",
    CoreNavigation               : "CoreNavigation",
    CoreOtpInput                 : "CoreOtpInput",
    CoreOutlinedButton           : "CoreOutlinedButton",
    CorePaper                    : "CorePaper",
    CorePhone                    : "CorePhone",
    CorePhoneLink                : "CorePhoneLink",
    CorePopover                  : "CorePopover",
    CoreProfilePopOver           : "CoreProfilePopOver",
    CoreRating                   : "CoreRating",
    CoreReactSelectInput         : "CoreReactSelectInput",
    CoreRequestProgressBar       : "CoreRequestProgressBar",
    CoreResponsiveButton         : "CoreResponsiveButton",
    CoreRichTextEditor           : "CoreRichTextEditor",
    CoreRightDrawer              : "CoreRightDrawer",
    CoreScrollTop                : "CoreScrollTop",
    CoreSection                  : "CoreSection",
    CoreSelect                   : "CoreSelect",
    CoreSkeleton                 : "CoreSkeleton",
    CoreSnackbar                 : "CoreSnackbar",
    CoreSpan                     : "CoreSpan",
    CoreSpecificForm             : "CoreSpecificForm",
    CoreStack                    : "CoreStack",
    CoreSwitch                   : "CoreSwitch",
    CoreTab                      : "CoreTab",
    CoreTabHead                  : "CoreTabHead",
    CoreTabPanel                 : "CoreTabPanel",
    CoreTable                    : "CoreTable",
    CoreTableAction              : "CoreTableAction",
    CoreTableBody                : "CoreTableBody",
    CoreTableBodyCell            : "CoreTableBodyCell",
    CoreTableBulkAction          : "CoreTableBulkAction",
    CoreTableCell                : "CoreTableCell",
    CoreTableCollapsible         : "CoreTableCollapsible",
    CoreTableContainer           : "CoreTableContainer",
    CoreTableFilter              : "CoreTableFilter",
    CoreTableFooter              : "CoreTableFooter",
    CoreTableHead                : "CoreTableHead",
    CoreTableHeadCell            : "CoreTableHeadCell",
    CoreTableHeadRow             : "CoreTableHeadRow",
    CoreTablePagination          : "CoreTablePagination",
    CoreTableRow                 : "CoreTableRow",
    CoreTableSkeleton            : "CoreTableSkeleton",
    CoreTableSortLabel           : "CoreTableSortLabel",
    CoreTableToolBar             : "CoreTableToolBar",
    CoreTabs                     : "CoreTabs",
    CoreTermsPrivacyLink         : "CoreTermsPrivacyLink",
    CoreTextButton               : "CoreTextButton",
    CoreTextField                : "CoreTextField",
    CoreTextarea                 : "CoreTextarea",
    CoreTimePicker               : "CoreTimePicker",
    CoreTimeRangePicker          : "CoreTimeRangePicker",
    CoreToolbar                  : "CoreToolbar",
    CoreTooltip                  : "CoreTooltip",
    CoreTypography               : "CoreTypography",
    CoreTypographyBody1          : "CoreTypographyBody1",
    CoreTypographyBody2          : "CoreTypographyBody2",
    CoreTypographyButton         : "CoreTypographyButton",
    CoreTypographyCaption        : "CoreTypographyCaption",
    CoreTypographyOverline       : "CoreTypographyOverline",
    CoreTypographySubtitle1      : "CoreTypographySubtitle1",
    CoreTypographySubtitle2      : "CoreTypographySubtitle2",
    CoreViewField                : "CoreViewField",
    CoreViewForm                 : "CoreViewForm",
    // DevCoreDataTable             : "DevCoreDataTable",
    // ExportData                   : "ExportData",
    // FilterColumn                 : "FilterColumn",
    // FilterData                   : "FilterData",
    // HelpAndSupportPopOver        : "HelpAndSupportPopOver",
    // Logout                       : "Logout",
    // NotificationPopOver          : "NotificationPopOver",
    // ParentChildMap               : "ParentChildMap",
    // QuickAddPopOver              : "QuickAddPopOver",
    // SortTableData                : "SortTableData",
    // SplashComponent              : "SplashComponent",
    // StatusText                   : "StatusText",
    // TableDensity                 : "TableDensity",
    // TableRowAuditData            : "TableRowAuditData",
    // UserChip                     : "UserChip",
    // WrappidComponent             : "WrappidComponent"
  };